services:
    _defaults:
        autowire: true
        autoconfigure: true

    PBaszak\MessengerDoctrineDTOBundle\:
        resource: '../../*'
        exclude:
            - '../../{Resources,DependencyInjection,MessengerDoctrineDTOBundle.php}'
