set -e

echo "host ${APP_DB} ${APP_USER} 10.0.0.0/8 trust" >>"$PGDATA/pg_hba.conf"

psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $POSTGRES_DB;
EOSQL

psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_USER WITH ENCRYPTED PASSWORD '$POSTGRESS_PASSWORD';
EOSQL

psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION $POSTGRES_USER;
    GRANT ALL ON SCHEMA public TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=0 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $APP_DB;
    CREATE USER $APP_USER WITH ENCRYPTED PASSWORD '$APP_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $APP_USER;
EOSQL

psql -v ON_ERROR_STOP=0 --username "$APP_USER" --dbname "$APP_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS $APP_SCHEMA AUTHORIZATION $APP_USER;
    GRANT ALL ON SCHEMA $APP_SCHEMA TO $APP_USER;
EOSQL
