framework:
    handle_all_throwables: true
    http_method_override: false
    php_errors:
        log: true
    secret: '%env(APP_SECRET)%'
    test: true

parameters:
    db_schema: '%env(string:POSTGRES_SCHEMA)%'
    env(POSTGRES_DB): doctrine_dto
    env(POSTGRES_PASSWORD): ZTB6JpziG6171smtiqt0
    env(POSTGRES_USER): doctrine_dto
    env(POSTGRES_SCHEMA): doctrine_dto

services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    PBaszak\MessengerDoctrineDTOBundle\Tests\Helper\:
        resource: '../tests/Helper/'
        exclude:
            - '../tests/Helper/Application/Entity/'
            - '../tests/Helper/Kernel.php'

    messenger_doctrine_dto.cache.adapter.php_files:
        class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
        public: true
        arguments:
            - messenger_doctrine_dto.mapper
            - 0
            - null
            - true
